---
# Task set definitions.
#
# Each set has the following parameters:
# - set_id: the set identifier used in paths and URLs (keep it simple, [-a-z0-9]+)
# - title: title for the set list (may contain HTML)
# - template: path to the ERB template used to render the task fragments
#
# Optional parameters:
# - show_csv_link: set to false to hide the CSV download link (default: true)
# - show_stable_id: set to true to show the stable task IDs on top of the page (default: false)
# - list_stable_id: set to true to show the stable task IDs in the task list (default: false)
# - decision_choices: name of the decision type (see decision_choices.yml, default = default)
#
# Any additional parameters are available through the parameters field of the set object.
#
- set_id: example-png
  title: Example with PNG images in per-subject directories
  template: task-views/all-images.erb
- set_id: example-mp4
  title: Example with MP4 video
  template: task-views/all-mp4s.erb
- set_id: example-nifti
  title: Example with NIFTI viewer
  template: task-views/all-nii-gzs.erb
- set_id: example-nifti-seg
  title: Example with NIFTI viewer with segmentation overlay
  template: task-views/nii-gz-segmentation.erb
